#!/bin/sh
#
# Wrapper for dragon heap image
#

case `uname -s` in
  Darwin) heap=dragon.ppc-darwin ;;
  *) heap=dragon.x86-linux ;;
esac

if test ! -r $heap ; then
  echo "dragon: no heap image!"
  exit 1
fi

exec sml @SMLload=$heap $@