(*
 * WARNING: This file was automatically generated by MDLGen (v3.0)
 * from the machine description file "mips/mips.mdl".
 * DO NOT EDIT this file directly
 *)


functor MIPSRTL(structure RTL : MLTREE_RTL
                structure C   : MIPSCELLS
               )=
struct
   structure T = RTL.T
   structure P = struct
   end

   fun LB {rt, b, d, mem} = T.ASSIGN (64, T.$ (64, C.GP, rt), T.SX (64, 8, 
          T.$ (8, C.MEM, T.ADD (64, T.$ (64, C.GP, b), d))))
   fun LBU {rt, b, d, mem} = T.ASSIGN (64, T.$ (64, C.GP, rt), T.ZX (64, 8, 
          T.$ (8, C.MEM, T.ADD (64, T.$ (64, C.GP, b), d))))
   fun LH {rt, b, d, mem} = T.ASSIGN (64, T.$ (64, C.GP, rt), T.SX (64, 16, 
          T.$ (8, C.MEM, T.ADD (64, T.$ (64, C.GP, b), d))))
   fun LHU {rt, b, d, mem} = T.ASSIGN (64, T.$ (64, C.GP, rt), T.ZX (64, 16, 
          T.$ (8, C.MEM, T.ADD (64, T.$ (64, C.GP, b), d))))
   fun LW {rt, b, d, mem} = T.ASSIGN (64, T.$ (64, C.GP, rt), T.SX (64, 32, 
          T.$ (8, C.MEM, T.ADD (64, T.$ (64, C.GP, b), d))))
   fun LD {rt, b, d, mem} = T.ASSIGN (64, T.$ (64, C.GP, rt), T.$ (8, C.MEM, 
          T.ADD (64, T.$ (64, C.GP, b), d)))
end

