(* skeleton-pickle.sig
 *
 * COPYRIGHT (c) 2025 The Fellowship of SML/NJ (https://smlnj.org)
 * All rights reserved.
 *
 * Interface to pickler for skeletons.  This signature is trimmed down
 * from what is generated by ASDLgen.
 *)

signature SKELETON_PICKLE = sig

    type instream
    type outstream

    val write_decl : outstream * Skeleton.decl -> unit
    val read_decl : instream -> Skeleton.decl

  end
