:version: 110.90
:date: June 12, 2019
:dist-dir: https://smlnj.org/dist/working/{version}/
:history: {dist-dir}HISTORY.html
:stem: latexmath
:source-highlighter: pygments
:stylesheet: release-notes.css
:notitle:

= Standard ML of New Jersey Release Notes

[subs=attributes]
++++
<div class="smlnj-banner">
  <span class="title"> Standard ML of New Jersey <br/> Release Notes </span>
  <br/> <br/>
  <span class="subtitle"> Version {version} <br/> {date} </span>
</div>
++++

''''''''
--
SML/NJ HOME::
  https://www.smlnj.org/index.html[[.tt]#https://smlnj.org#]
FILES::
  {dist-dir}index.html[[.tt]#{dist-dir}#]
--
''''''''

== Summary

The primary purpose of this release is to bring the Windows port of
SML/NJ up to parity with the Unix versions w.r.t. the 64-bit cleanup.
It also provides a fix for a long dormant bug in CM that was exposed
by the Basis reorganization in 110.88.

== Details

=== Installation

While the {dist-dir}smlnj-x86-{version}.pkg[installer]
for {version} works on macOS 10.14 Mojave, building from source
requires some extra steps.  Another issue that you may encounter
when building on macOS 10.14 Mojave is an error message for a shell
script of the form

.....
  /bin/sh: bad interpreter: Operation not permitted
.....

This error arises because the `com.apple.quarantine` attribute is set on the
shell script.  To fix the problem, remove the attribute using the command

[source,shell]
-----
  xattr -d com.apple.quarantine shell-script
-----
and resume the build.


=== Compiler

This compiler now supports a primitive type to represent pointers to runtime-system
data structures.  User-level access to this type is available via the `Unsafe.Pointer`
structure.  Note that these values (other than the null pointer) cannot persist
across heap exports.  In fact, exporting a heap that contains a pointer will
result in an error message.

=== Basis Library

This version implements the following Basis Library proposal:
--
**[2019-001]**::
https://github.com/SMLFamily/BasisLibrary/wiki/2019-001-Correction-to-PRIM_IO[__Correction to the PRIM_IO signature__] --
This proposal changes the return type of the `avail` function for readers to
return `Position.int option`, instead of `int option` type.
--

=== Runtime System

--
* The interface between the SML/NJ Basis code and the runtime system now uses unsigned 64-bit
  values to communicate time information (__e.g.__, for the current time or file-modification
  timestamps).  The Windows code that works with time and date values now uses the native
  Windows API, instead of the C-Library API.

* The handling of 32-bit values in the runtime system has been modified to allow for
  both boxed representations (on 32-bit machines) and tagged representations (on 64-bit
  machines).

* The runtime and Basis representation of the Microsoft `HANDLE` type has been abstracted
  over the target-machine word size.  While this type is an alias for `void *`, the
  values are not actually pointers; therefore we represent them as boxed words of the native
  machine size.
--


== Bugs

Here is a list of tracked bugs fixed (or closed) with this release, please see the
https://smlnj-gforge.cs.uchicago.edu/projects/smlnj-bugs[bug tracker]
for more details.

[.buglist,cols="^1,<15"]
|=======
| [.bugid]#222#
| CM exports from imported library rather than from defined library
|=======


== Supported systems

We believe that SML/NJ will build and run on the following systems, but have only
tested some of them:

[.support-table,cols="^2s,^4v,^3v",options="header",strips="none"]
|=======
| Architecture | Operating System | Status
| Power PC | Mac OS X 10.5 (Leopard) |
| | AIX |
| {nbsp} | |
| Sparc | Solaris |
| | Linux |
| {nbsp} | |
| x86 (32-bit) | Mac OS X 10.6 (Snow Leopard) |
| | Mac OS X 10.7 (Lion) |
| | Mac OS X 10.8 (Mountain Lion) |
| | Mac OS X 10.9 (Mavericks) |
| | Mac OS X 10.10 (Yosemite) |
| | Mac OS X 10.11 (El Capitan) |
| | macOS 10.12 (Sierra) | Tested
| | macOS 10.13 (High Sierra) | Tested
| | macOS 10.14 (Mojave) | Tested
| | Ubuntu 16.04.3 LTS | Tested
| | Other Linux variants |
| | BSD variants |
| | Windows 7 |
| | Windows 10 |
| | Cygwin (32-bit) |
|=======

=== A note about 64-bit support

Apple is in the process of deprecating 32-bit support in macOS.
With macOS 10.14 Mojave, compiling 32-bit applications, such as the SML/NJ
runtime system, requires using an older SDK.
The SML/NJ {dist-dir}smlnj-x86-{version}.pkg[installer],
however, works without issue on macOS 10.14 Mojave.

We have been working on 64-bit support since 110.82 we expect to have it in place
before the release of macOS 10.15.
