:version: 2023.1
:date: @DATE@
:dist-dir: https://smlnj.org/dist/working/{version}/
:history: {dist-dir}HISTORY.html
:issue-base: https://github.com/smlnj/smlnj/issues
:legacy-issue-base: https://github.com/smlnj/legacy/issues
:pull-base: https://github.com/smlnj/smlnj/pull
:stem: latexmath
:source-highlighter: pygments
:stylesheet: release-notes.css
:notitle:

= Standard ML of New Jersey Release Notes

[subs=attributes]
++++
<div class="smlnj-banner">
  <span class="title"> Standard ML of New Jersey <br/> Release Notes </span>
  <br/> <br/>
  <span class="subtitle"> Version {version} <br/> {date} </span>
</div>
++++

''''''''
--
SML/NJ HOME::
  https://www.smlnj.org/index.html[[.tt]#https://smlnj.org#]
FILES::
  {dist-dir}index.html[[.tt]#{dist-dir}#]
--
''''''''

== Summary

This is a bug-fix release of the development version of **SML/NJ**.
The most important fix is that the system now correctly supports
**Linux** and the latest versions of **macOS**.  This release also
incorporates a number of fixes for issues fixed in the legacy version
https://smlnj.org/dist/working/110.99.4/index.html[110.99.4].

== Details

// **** details: include those sections that are relevant

=== Compiler

=== CM

=== MLRISC

=== Runtime System

=== Basis Library

=== SML/NJ Library

=== Successor ML

=== ML-LPT

=== Documentation

=== Installation

=== 32-bit macOS issues

While the {dist-dir}smlnj-x86-{version}.pkg[x86 installer]
for {version} works on **macOs** 10.14 Mojave, building from source
requires some extra steps because the version of **Xcode**
distributed for Mojave does not include a 32-bit SDK.

Another issue that you may encounter
when building on **macOs** 10.14 Mojave is an error message for a shell
script of the form

.....
  /bin/sh: bad interpreter: Operation not permitted
.....

This error arises because the `com.apple.quarantine` attribute is set on the
shell script.  To fix the problem, remove the attribute using the command

[source,shell]
-----
  xattr -d com.apple.quarantine shell-script
-----
and resume the build.

== Bugs

Here is a list of the issues that are fixed (or closed) with this release.

[.buglist,cols="^1,<15",strips="none",options="header"]
|=======
| Issue
| Description
| [.bugid]#233#
| {issue-base}/233[Installation of SML/NJ 2021.1 fails on Ubuntu 20.04]
| [.bugid]#272#
| {issue-base}/272[Unable to build LLVM when running `build.sh`]
| [.bugid]#276#
| {issue-base}/276[`UTF8.getu` should validate that it's input is UTF-8]
// | [.bugid]#@ID@#
// | @DESCRIPTION@
|=======

We also fixed the following bugs that did not have issues
associated with them (or were bug fixes ported from the legacy
repository):

--
* {legacy-issue-base}/87[`ml-makedepend` trashes dependency file on error]
* {legacy-issue-base}/256[Initial numbers generated by `Util/random.sml` have unexpected regularities]
* {legacy-issue-base}/258[Thompson NFA regex engine doesn’t advance stream position when matching]
* {legacy-issue-base}/278[`CharBuffer.addSlice` does not properly handle starting offsets]
* {legacy-issue-base}/279[`HashSetFn`'s calculation of `maxSize` can cause `Overflow` during functor instantiation]
* {legacy-issue-base}/287[The word literal `0wx80000000` is incorrectly converted to `0wx7FFFFFFF80000000`]
* The `ULexBuffer.getu` function did not handle 4-byte UTF-8 sequences in some
  situations.
* The `ULexBuffer.getu` function did not reject surrogate halves or too-large codepoints.
--

== Supported systems

We believe that SML/NJ will build and run on the following systems, but have only
tested some of them:

[.support-table,cols="^2s,^4v,^3v",options="header",strips="none"]
|=======
| Architecture | Operating System | Status
| AMD64 | |
| | macOS 11 (Big Sur) | Tested
| | macOS 12 (Monterey) | Tested
| | macOS 13 (Ventura) |
| | macOS 14 (Sonoma) |
| | Ubuntu 20.04.6 LTS | Tested
| | Ubuntu 22.04.2 LTS | Tested
| {nbsp} | |
|=======
