:version: 2024.1
:date: @DATE@
:dist-dir: https://smlnj.org/dist/working/{version}/
:history: {dist-dir}HISTORY.html
:issue-base: https://github.com/smlnj/smlnj/issues
:legacy-issue-base: https://github.com/smlnj/legacy/issues
:pull-base: https://github.com/smlnj/smlnj/pull
:legacy-pull-base: https://github.com/smlnj/legacy/pull/
:stem: latexmath
:source-highlighter: pygments
:stylesheet: release-notes.css
:notitle:

= Standard ML of New Jersey Release Notes

[subs=attributes]
++++
<div class="smlnj-banner">
  <span class="title"> Standard ML of New Jersey <br/> Release Notes </span>
  <br/> <br/>
  <span class="subtitle"> Version {version} <br/> {date} </span>
</div>
++++

''''''''
--
SML/NJ HOME::
  https://www.smlnj.org/index.html[[.tt]#https://smlnj.org#]
FILES::
  {dist-dir}index.html[[.tt]#{dist-dir}#]
--
''''''''

== Summary

// **** summary description of release

== Details

// **** details: include those sections that are relevant

=== Compiler

=== CM

=== MLRISC

=== Runtime System

=== Basis Library

=== SML/NJ Library

=== Successor ML

=== ML-LPT

=== Documentation

=== Installation

=== 32-bit macOS issues

While the {dist-dir}smlnj-x86-{version}.pkg[x86 installer]
for {version} works on **macOs** 10.14 Mojave, building from source
requires some extra steps because the version of **Xcode**
distributed for Mojave does not include a 32-bit SDK.

Another issue that you may encounter
when building on **macOs** 10.14 Mojave is an error message for a shell
script of the form

.....
  /bin/sh: bad interpreter: Operation not permitted
.....

This error arises because the `com.apple.quarantine` attribute is set on the
shell script.  To fix the problem, remove the attribute using the command

[source,shell]
-----
  xattr -d com.apple.quarantine shell-script
-----
and resume the build.

== Bugs

Here is a list of the issues that are fixed (or closed) with this release.

[.buglist,cols="^1,<15",strips="none",options="header"]
|=======
| Issue
| Description
| [.bugid]#279#
| {issue-base}/279["Unable to build LLVM" error with 2023.1]
| [.bugid]#280#
| {pull-base}/280[`DynamicArray.subArray` creates array with length bound+1]
| [.bugid]#284#
| {issue-base}/284[Incorrect printing of source code in error message]
// | [.bugid]#@ID#
// | @DESCRIPTION@
|=======

We also fixed the following bugs that did not have issues
associated with them (or were bug fixes ported from the legacy
repository):
--
* {legacy-issue-base}/286[Get "fgrep is obsolescent" when run *sml* on Fedora]

* {legacy-issue-base}/297[Additional operations for the `MONO_HASH_TABLE` interface]

* The implementations of `PackWord64Little.update` and `PackWord64Big.update`
  were swapped on 64-bit platforms.
--

== Supported systems

We believe that SML/NJ will build and run on the following systems, but have only
tested some of them:

[.support-table,cols="^2s,^4v,^3v",options="header",strips="none"]
|=======
| Architecture | Operating System | Status
| AMD64 | |
| | macOS 11 (Big Sur) |
| | macOS 12 (Monterey) | Tested
| | macOS 13 (Ventura) | Tested
| | macOS 14 (Sonoma) | Tested
| | Ubuntu 20.04.6 LTS | Tested
| | Ubuntu 22.04.2 LTS | Tested
| {nbsp} | |
|=======
