= Installing SML/NJ on Unix
:revnumber: {version}
:revdate: {release-date}
:source-highlighter: pygments
:dist-dir: https://smlnj.org/dist/working/{version}/
:history: {dist-dir}HISTORY.html
:release-notes: {dist-dir}{version}-README.html
:stem: latexmath
:source-highlighter: pygments

These instructions are for installing the development version
of **Standard ML of New Jersey** (**SML/NJ**) on **Unix** and
Unix-like operating systems (including **Linux** and **macOS**).

--
1. clone the repository for version {version}.
+
[subs="+attributes"]
----
 git clone --depth 1 --branch v{version} --recurse-submodules https://github.com/smlnj/smlnj.git
----
+
Note that you can also clone the entire repository and then switch to the
`v{version}` tag.
+
The `--depth` option limits the download to just one commit (_i.e._, no
history), the `--branch` option specifies the version of the source
code that you are requesting, and the `--recurse-submodules` option is
necessary to fetch the customized version of the **LLVM** library that we
use.

2. `cd` to the cloned repository and build the system.
+
----
 cd smlnj
 ./build.sh
----
Use `build.sh -h` to see the list of options accepted by the build script.
+
As before, you can modify the `config/targets` file to add/remove components
from the build.
--

After successful running of the `build.sh` script, `bin/sml` will be the interactive
system.
