= The `LEB128` structure
:Author: John Reppy
:Date: {release-date}
:stem: latexmath
:source-highlighter: pygments
:VERSION: {smlnj-version}

The `LEB128` structure provides binary encoding/decoding of integer and word types
using the https://en.wikipedia.org/wiki/LEB128[Little-Endian-Base-128 (LEB128)]
format.  It supports signed and unsigned encodings, decodings, and functions to
precompute encoding sizes.

== Synopsis

[source,sml]
------------
signature LEB128
structure LEB128 : LEB128
------------

== Interface

[source,sml]
------------
type ('ty, 'src) decoder =
      (Word8.word, 'src) StringCvt.reader -> 'src -> ('ty * 'src) option

val decodeInt       : (Int.int, 'a) decoder
val decodeNativeInt : (NativeInt.int, 'a) decoder
val decodeInt64     : (Int64.int, 'a) decoder
val decodeIntInf    : (IntInf.int, 'a) decoder

val decodeWord       : (Word.word, 'src) decoder
val decodeNativeWord : (NativeWord.word, 'src) decoder
val decodeWord64     : (Word64.word, 'src) decoder
val decodeUIntInf    : (IntInf.int, 'src) decoder

type 'ty encoder = 'ty -> Word8Vector.vector

val encodeInt       : Int.int encoder
val encodeNativeInt : Int64.int encoder
val encodeInt64     : Int64.int encoder
val encodeIntInf    : IntInf.int encoder

val encodeWord       : Word.word encoder
val encodeNativeWord : Word64.word encoder
val encodeWord64     : Word64.word encoder
val encodeUIntInf    : IntInf.int encoder

val sizeOfInt       : Int.int -> int
val sizeOfNativeInt : NativeInt.int -> int
val sizeOfInt64     : Int64.int -> int
val sizeOfIntInf    : IntInf.int -> int

val sizeOfWord       : Word.word -> int
val sizeOfNativeWord : NativeWord.word -> int
val sizeOfWord64     : Word64.word -> int
val sizeOfUIntInf    : IntInf.int -> int
------------

== Description

The `LEB128` structure provides three kinds of operations: decoders, encoders,
and size functions.

=== Decoding

The decoding functions take a reader and input source and return an optional result.
These functions normally return `SOME(value, rest)`, where `value` is the decoded
number and `rest` is the residual input source.  There are two possible error
conditions for decoding.  If the input is incomplete (_i.e._, empty or a ends
with a byte that has the continuation bit set), then `NONE` is returned.  If the
decoded value is too large for the type, then the link:{sml-basis-url}/general.html#SIG:GENERAL.Overflow:EXN:SPEC[`Overflow`]
exception is raised.

`[.kw]#type# ('ty, 'src) decoder`
  the type of a decoder that decodes values of type `'ty` from a byte
  source of type `src`.

`[.kw]#val# decodeInt : (Int.int, 'a) decoder`::
  `decodeInt getb src` decodes an LEB128 encoded integer from `src` using `getb` to
  read bytes from the `src`.

`[.kw]#val# decodeNativeInt : (NativeInt.int, 'a) decoder`::
  `decodeNativeInt getb src` decodes an LEB128 encoded native-machine integer
  from `src` using `getb` to read bytes from the `src`.

`[.kw]#val# decodeInt64 : (Int64.int, 'a) decoder`::
  `decodeInt64 getb src` decodes an LEB128 encoded integer from `src` using `getb` to
  read bytes from the `src`.

`[.kw]#val# decodeIntInf : (IntInf.int, 'a) decoder`::
  `decodeIntInf getb src` decodes an LEB128 encoded integer from `src` using `getb` to
  read bytes from the `src`.  Note that this decoder does not raise the
  link:{sml-basis-url}/general.html#SIG:GENERAL.Overflow:EXN:SPEC[`Overflow`] exception.

`[.kw]#val# decodeWord : (Word.word, 'src) decoder`::
  `decodeWord getb src` decodes an LEB128 encoded word from `src` using `getb` to
  read bytes from the `src`.

`[.kw]#val# decodeNativeWord : (NativeWord.word, 'src) decoder`::
  `decodeNativeWord getb src` decodes an LEB128 encoded word from `src` using `getb` to
  read bytes from the `src`.

`[.kw]#val# decodeWord64 : (IntInf.int, 'src) decoder`::
  `decodeWord64 getb src` decodes an LEB128 encoded word from `src` using `getb` to
  read bytes from the `src`.

`[.kw]#val# decodeUIntInf : (IntInf.int, 'src) decoder`::
  `decodeUIntInf getb src` decodes an LEB128 encoded unsigned integer from `src`
  using `getb` to read bytes from the `src`.  Note that this decoder does not raise the
  link:{sml-basis-url}/general.html#SIG:GENERAL.Overflow:EXN:SPEC[`Overflow`]
  exception.

=== Encoding

`[.kw]#type# 'ty encoder`::
  the type of a encoder for values of type `'ty`.

`[.kw]#val# encodeInt : Int.int encoder`::
  `encodeInt n` returns the LEB128 encoding of the signed integer `n`.

`[.kw]#val# encodeNativeInt : NativeInt.int encoder`::
  `encodeNativeInt n` returns the LEB128 encoding of the signed integer `n`.

`[.kw]#val# encodeInt64 : Int64.int encoder`::
  `encodeInt64 n` returns the LEB128 encoding of the signed integer `n`.

`[.kw]#val# encodeIntInf : IntInf.int encoder`::
  `encodeIntInf n` returns the LEB128 encoding of the signed integer `n`.

`[.kw]#val# encodeWord : Word.word encoder`::
  `encodeWord w` returns the LEB128 encoding of the word `w`.

`[.kw]#val# encodeNativeWord : NativeWord.word encoder`::
  `encodeNativeWord w` returns the LEB128 encoding of the word `w`.

`[.kw]#val# encodeWord64 : Word64.word encoder`::
  `encodeWord64 w` returns the LEB128 encoding of the word `w`.

`[.kw]#val# encodeUIntInf : IntInf.int encoder`::
  `encodeUIntInf n` returns the LEB128 encoding of the unsigned integer `n`.
  This expression will raise the
  link:{sml-basis-url}/general.html#SIG:GENERAL.Domain:EXN:SPEC[`Domain`]
  exception when `n < 0`.

=== Encoding Size

The remaining operations compute the number of bytes required to encode a
number.

`[.kw]#val# sizeOfInt : Int.int -> int`::
  `sizeOfInt n` returns the size in bytes of the LEB128 encoding of the
  signed integer `n`.

`[.kw]#val# sizeOfNativeInt : NativeInt.int -> int`::
  `sizeOfNativeInt n` returns the size in bytes of the LEB128 encoding of the
  signed integer `n`.

`[.kw]#val# sizeOfInt64 : Int64.int -> int`::
  `sizeOfInt64 n` returns the size in bytes of the LEB128 encoding of the
  signed integer `n`.

`[.kw]#val# sizeOfIntInf : IntInf.int -> int`::
  `sizeOfIntInf n` returns the size in bytes of the LEB128 encoding of the
  signed integer `n`.

`[.kw]#val# sizeOfWord : Word.word -> int`::
  `sizeOfWord w` returns the size in bytes of the LEB128 encoding of the word `w`.

`[.kw]#val# sizeOfNativeWord : NativeWord.word -> int`::
  `sizeOfNativeWord w` returns the size in bytes of the LEB128 encoding of the word `w`.

`[.kw]#val# sizeOfWord64 : Word64.word -> int`::
  `sizeOfWord64 w` returns the size in bytes of the LEB128 encoding of the word `w`.

`[.kw]#val# sizeOfUIntInf : IntInf.int -> int`::
  `sizeOfUIntInf n` returns the size in bytes of the LEB128 encoding of the
  unsigned integer `n`.
  This expression will raise the
  link:{sml-basis-url}/general.html#SIG:GENERAL.Domain:EXN:SPEC[`Domain`]
  exception when `n < 0`.

== See Also

xref:smlnj-lib.adoc[__The Util Library__]
